## <font color='green'> <div align="center">In the name of God </div></font>

### <font color='red'> Author: Sayed Kamaledin Ghiasi-Shrirazi</font> <a href="http://profsite.um.ac.ir/~k.ghiasi">(http://profsite.um.ac.ir/~k.ghiasi)</a> 

# Studying ConvTransposed2D-Example 1

### importing general modules

In [1]:
import numpy as np
import scipy.io as sio
import matplotlib as mpl
import matplotlib.pyplot as plt

### importing PyTorch modules

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

## Defining the network by inheriting from nn.Module

In [3]:
layer  = nn.ConvTranspose2d(in_channels=1,
                                        out_channels=1,
                                        kernel_size=3,
                                        stride=1,
                                        padding=0,
                                        output_padding=0,
                                        groups=1,
                                        bias=True,
                                        dilation=1)

In [4]:
layer.bias[0] = 0
layer.weight[0,0,0,0] = 1
layer.weight[0,0,0,1] = 2
layer.weight[0,0,0,2] = 3

layer.weight[0,0,1,0] = 4
layer.weight[0,0,1,1] = 5
layer.weight[0,0,1,2] = 6

layer.weight[0,0,2,0] = 7
layer.weight[0,0,2,1] = 8
layer.weight[0,0,2,2] = 9

In [5]:
layer.weight

Parameter containing:
tensor([[[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]], grad_fn=<CopySlices>)

In [6]:
H = 1
W = 1
X = np.zeros([1,1,H,W])
X[0,0,0,0] = 1
X = torch.tensor (X, dtype=torch.float)
Y = layer(X)
print (Y)

tensor([[[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]], grad_fn=<SlowConvTranspose2DBackward>)


In [9]:
H = 2
W = 2
X = np.zeros([1,1,H,W])
X[0,0,0,0] = 1
X[0,0,0,1] = 2

X[0,0,1,0] = 2
X[0,0,1,1] = 1

X = torch.tensor (X, dtype=torch.float)
Y = layer(X)
print (Y)

tensor([[[[ 1.,  4.,  7.,  6.],
          [ 6., 18., 24., 15.],
          [15., 36., 42., 24.],
          [14., 23., 26.,  9.]]]], grad_fn=<SlowConvTranspose2DBackward>)
